#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa deps/protobuffs/ebin debug verbose  
main(_) ->
    protobuffs_compile:generate_source("./priv/popcorn.proto", [{output_include_dir, "include"}, {output_src_dir, "src"}]).


